spring.application.name=demo

########## CONEXIÓN BASE DE DATOS #########

# PRODUCCIÓN (variables de entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# opcional (pool)
spring.datasource.hikari.maximum-pool-size=5

# puerto dinámico (Render)
server.port=${PORT:8080}