spring.application.name=demo

########## CONEXI�N BASE DE DATOS #########

# PRODUCCI�N (variables de entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# LOCAL / RESPALDO (NO USAR EN PRODUCCI�N)
#spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
#spring.datasource.username=postgres.ysrnzwyqehdlgtfplxkh
#spring.datasource.password=ContraPrueba

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# opcional (pool)
spring.datasource.hikari.maximum-pool-size=5

# puerto din�mico (Render)
server.port=${PORT:8080}